---
- name: CVE-SEARCH - Update CPE
  shell: "{{ apps_volume }}/CVE-SEARCH/env/bin/python ./sbin/db_mgmt_cpe_dictionary.py -p"
  args:
    chdir: "{{ apps_volume }}/CVE-SEARCH"

- name: CVE-SEARCH - Update all DBs and indexes
  shell: "{{ apps_volume }}/CVE-SEARCH/env/bin/python ./sbin/db_mgmt_json.py -p"
  args:
    chdir: "{{ apps_volume }}/CVE-SEARCH"

- name: CVE-SEARCH - Update all DBs and indexes
  shell: "{{ apps_volume }}/CVE-SEARCH/env/bin/python ./sbin/db_updater.py -c"
  args:
    chdir: "{{ apps_volume }}/CVE-SEARCH"

- name: CVE-SEARCH - Update VIA references
  shell: "{{ apps_volume }}/CVE-SEARCH/env/bin/python ./sbin/db_mgmt_ref.py"
  args:
    chdir: "{{ apps_volume }}/CVE-SEARCH"
