# Generated by Django 3.1.14 on 2024-11-11 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cves', '0019_auto_20240209_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='assigner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cves.product'),
        ),
    ]
