# Generated by Django 3.1.14 on 2024-11-12 08:46

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220419_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorgsettings',
            name='alerts_telegram',
            field=models.JSONField(default=users.models.telegram_dict),
        ),
        migrations.AddField(
            model_name='historicalorgsettings',
            name='alerts_telegram_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='alerts_telegram',
            field=models.JSONField(default=users.models.telegram_dict),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='alerts_telegram_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
